// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product/app/v1/v1.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetArticlesReq struct {
	// @inject_tag: form:"title"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty" form:"title"`
	// @inject_tag: form:"page"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty" form:"page"`
	// @inject_tag: form:"page_size" binding:"required"
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" form:"page_size" binding:"required"`
	// @inject_tag: form:"author_id" uri:"author_id"
	AuthorId             int32    `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty" form:"author_id" uri:"author_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticlesReq) Reset()         { *m = GetArticlesReq{} }
func (m *GetArticlesReq) String() string { return proto.CompactTextString(m) }
func (*GetArticlesReq) ProtoMessage()    {}
func (*GetArticlesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{0}
}

func (m *GetArticlesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticlesReq.Unmarshal(m, b)
}
func (m *GetArticlesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticlesReq.Marshal(b, m, deterministic)
}
func (m *GetArticlesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticlesReq.Merge(m, src)
}
func (m *GetArticlesReq) XXX_Size() int {
	return xxx_messageInfo_GetArticlesReq.Size(m)
}
func (m *GetArticlesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticlesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticlesReq proto.InternalMessageInfo

func (m *GetArticlesReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetArticlesReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetArticlesReq) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetArticlesReq) GetAuthorId() int32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type GetArticlesResp struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Articles             []*Article `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetArticlesResp) Reset()         { *m = GetArticlesResp{} }
func (m *GetArticlesResp) String() string { return proto.CompactTextString(m) }
func (*GetArticlesResp) ProtoMessage()    {}
func (*GetArticlesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{1}
}

func (m *GetArticlesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticlesResp.Unmarshal(m, b)
}
func (m *GetArticlesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticlesResp.Marshal(b, m, deterministic)
}
func (m *GetArticlesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticlesResp.Merge(m, src)
}
func (m *GetArticlesResp) XXX_Size() int {
	return xxx_messageInfo_GetArticlesResp.Size(m)
}
func (m *GetArticlesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticlesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticlesResp proto.InternalMessageInfo

func (m *GetArticlesResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetArticlesResp) GetArticles() []*Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

type Article struct {
	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// @inject_tag: form:"author_id" uri:"author_id"
	AuthorId             int32    `protobuf:"varint,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty" form:"author_id" uri:"author_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{2}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Article) GetAuthorId() int32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetArticlesReq)(nil), "product.app.v1.GetArticlesReq")
	proto.RegisterType((*GetArticlesResp)(nil), "product.app.v1.GetArticlesResp")
	proto.RegisterType((*Article)(nil), "product.app.v1.Article")
}

func init() { proto.RegisterFile("product/app/v1/v1.proto", fileDescriptor_c6090e3745c002b5) }

var fileDescriptor_c6090e3745c002b5 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x4f, 0xc2, 0x30,
	0x18, 0xcd, 0x36, 0x10, 0x28, 0x8a, 0x49, 0x63, 0xc2, 0x82, 0x46, 0x60, 0x17, 0xb9, 0xb0, 0x66,
	0x70, 0xf0, 0xe0, 0x49, 0x88, 0x31, 0x5e, 0x47, 0xe2, 0x81, 0x98, 0x90, 0x32, 0x4a, 0xa9, 0x19,
	0x6b, 0xdd, 0xba, 0x45, 0x31, 0x5e, 0xf4, 0xe0, 0x0f, 0xf0, 0xa7, 0xf9, 0x17, 0xfc, 0x21, 0x86,
	0x6e, 0x10, 0x67, 0x82, 0x9e, 0xb6, 0xf7, 0xbd, 0xb7, 0xbd, 0xf7, 0xda, 0x0f, 0xd4, 0x45, 0xc8,
	0x67, 0xb1, 0x27, 0x11, 0x16, 0x02, 0x25, 0x0e, 0x4a, 0x1c, 0x5b, 0x84, 0x5c, 0x72, 0x58, 0xcb,
	0x08, 0x1b, 0x0b, 0x61, 0x27, 0x4e, 0xe3, 0x84, 0x72, 0x4e, 0x7d, 0x82, 0xb0, 0x60, 0x08, 0x07,
	0x01, 0x97, 0x58, 0x32, 0x1e, 0x44, 0xa9, 0xda, 0x92, 0xa0, 0x76, 0x4d, 0xe4, 0x65, 0x28, 0x99,
	0xe7, 0x93, 0xc8, 0x25, 0x0f, 0xf0, 0x08, 0x14, 0x25, 0x93, 0x3e, 0x31, 0xb5, 0x96, 0xd6, 0xa9,
	0xb8, 0x29, 0x80, 0x10, 0x14, 0x04, 0xa6, 0xc4, 0xd4, 0x5b, 0x5a, 0xa7, 0xe8, 0xaa, 0x77, 0x78,
	0x0c, 0x2a, 0xeb, 0xe7, 0x24, 0x62, 0x2b, 0x62, 0x1a, 0x8a, 0x28, 0xaf, 0x07, 0x23, 0xb6, 0x52,
	0x24, 0x8e, 0xe5, 0x82, 0x87, 0x13, 0x36, 0x33, 0x0b, 0x29, 0x99, 0x0e, 0x6e, 0x66, 0xd6, 0x1d,
	0x38, 0xcc, 0xb9, 0x46, 0x42, 0xd9, 0x72, 0x89, 0x7d, 0x65, 0x6b, 0xb8, 0x29, 0x80, 0x7d, 0x50,
	0xc6, 0x99, 0xca, 0xd4, 0x5b, 0x46, 0xa7, 0xda, 0xab, 0xdb, 0xf9, 0x7e, 0x76, 0xf6, 0x17, 0x77,
	0x2b, 0xb4, 0x6e, 0x41, 0x29, 0x1b, 0xee, 0x28, 0x63, 0x82, 0x92, 0xc7, 0x03, 0x49, 0x02, 0xa9,
	0xfa, 0x54, 0xdc, 0x0d, 0xcc, 0xa7, 0x36, 0xf2, 0xa9, 0x7b, 0x6f, 0x3a, 0xa8, 0x0e, 0x7c, 0x4e,
	0x47, 0x24, 0x4c, 0x98, 0x47, 0xe0, 0xbb, 0x06, 0xaa, 0x3f, 0x6a, 0xc0, 0xd3, 0xdf, 0xd1, 0xf2,
	0x27, 0xdb, 0x68, 0xfe, 0xc9, 0x47, 0xc2, 0x3a, 0x7f, 0xfd, 0xfc, 0xfa, 0xd0, 0x1d, 0xb8, 0xbf,
	0xbe, 0xd0, 0x4d, 0x9d, 0x71, 0x1b, 0x36, 0x15, 0x56, 0x31, 0xd0, 0xf3, 0x36, 0xdf, 0xcb, 0x56,
	0x02, 0xef, 0xc1, 0xc1, 0x30, 0x24, 0x58, 0x92, 0x4d, 0xef, 0x5d, 0xa7, 0xd4, 0xd8, 0x45, 0x58,
	0x67, 0xca, 0xbb, 0x6d, 0xfd, 0xe7, 0x35, 0xb8, 0x1a, 0x0f, 0x29, 0x93, 0x8b, 0x78, 0x6a, 0x7b,
	0x7c, 0x89, 0x12, 0x1c, 0xfa, 0xf1, 0x7c, 0xfe, 0x84, 0xd4, 0x3a, 0x79, 0x5d, 0x4a, 0x82, 0x2e,
	0xe5, 0x5d, 0xca, 0x02, 0x44, 0x1e, 0xf1, 0x52, 0x64, 0x8b, 0x97, 0x5f, 0xd6, 0x8b, 0xc4, 0x99,
	0xee, 0xa9, 0x0f, 0xfa, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x8b, 0x5e, 0xf3, 0xc8, 0x02,
	0x00, 0x00,
}
